name: Build Ubuntu

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'Src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'
          architecture: 'x64'
          cache: 'pip'

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: pip install --upgrade kivy https://github.com/kivymd/KivyMD/archive/master.zip

      - name: Build
        run: |
          

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 
          path: 
